# Generated by Django 5.2.6 on 2025-12-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="channel_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
