# Generated by Django 5.2.6 on 2025-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("sport", "Спорт"), ("fashion", "Мода"), ("News", "Новини")],
                default="tech",
                max_length=50,
            ),
        ),
    ]
