# Generated by Django 5.2.6 on 2025-12-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="articles.channel",
            ),
        ),
    ]
